export const BREAKPOINTS = [600, 900, 1200, 1800, 2500, 3000];

export const BREAKPOINT_XS = BREAKPOINTS[0];
export const BREAKPOINT_SM = BREAKPOINTS[1];
export const BREAKPOINT_MD = BREAKPOINTS[2];
export const BREAKPOINT_LG = BREAKPOINTS[3];
export const BREAKPOINT_XL = BREAKPOINTS[4];
