name: Deploy All

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-all:
    name: Deploy All
    runs-on: ubuntu-latest

    # Used to loop through each project and deploy it
    strategy:
      matrix:
        project: ["about"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: cd ./${{ matrix.project }} && npm i

      - name: Build project and copy images if there are any
        run: |
          cd ./${{ matrix.project }} && npm run build
          if [[ -d public/images ]]
          then
            echo "Copying images to build dir"
            cp -r public/images/ build/images/
          else
            echo "No images to be copied"
          fi
      
      # Push to Netlify
      - name: Push project build files to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_SITE_ID: "f121e096-98fa-4318-86d9-a44c89d6c708" 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: '${{ matrix.project }}/build'
