name: Deploy All

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-all:
    name: Deploy All
    runs-on: ubuntu-latest

    # Used to loop through each project and deploy it
    strategy:
      matrix:
        project: ["about", "writing", "photos", "music"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Only build if there are changes in project
        run: |
          count=$(git diff --name-only --diff-filter=ADMR --cached HEAD^ | grep -c ${{ matrix.project }}/)
          countShared=$(git diff --name-only --diff-filter=ADMR --cached HEAD^ | grep -c shared/)
          if [ $count -ge 1 ] || [ $countShared -ge 1 ]; then
            echo "Changes found, building project"
            echo "::set-output name=SHOULD_BUILD::true"
          else
            echo "No changes found in last commit"
            echo "::set-output name=SHOULD_BUILD::false"
          fi
      - name: Set up Node.js
        if: ${{ env.SHOULD_BUILD == 'true' }} 
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install shared deps
        if: ${{ env.SHOULD_BUILD == 'true' }} 
        run: cd ./shared && npm i && cd -

      - name: Install Node.js dependencies
        if: ${{ env.SHOULD_BUILD == 'true' }} 
        run: cd ./${{ matrix.project }} && npm i

      - name: Build Using Next.js Static Export
        if: ${{ env.SHOULD_BUILD == 'true' }} 
        run: |
          cd ./${{ matrix.project }} && npm run build
      
      # Push to repo will trigger Netlify deploy action in that repo
      - name: Push project build files to hosting repo
        if: ${{ env.SHOULD_BUILD == 'true' }} 
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '${{ matrix.project }}/build'
          destination-github-username: 'ebonsignori'
          destination-repository-name: 'my-${{ matrix.project }}'
          user-email: evanabonsignori@gmail.com
          target-branch: main
